#!/usr/bin/env python

import sys

from ostatus.hcard import hcard

def run():
    args = sys.argv
    for arg in args[1:]:
        data = hcard(arg)
        for key, value in data.items():
            print '%s: %s' % (key, value)

if __name__ == '__main__':
    run()
