#!/usr/bin/env python

import sys

from ostatus.status import status

def run():
    args = sys.argv
    for arg in args[1:]:
        entry = status(arg)
        print entry['updated']
        print '\t', entry['content']


if __name__ == '__main__':
    run()
