#!/usr/bin/env python

import sys

from ostatus.webfinger import finger

def run():
    args = sys.argv
    for arg in args[1:]:
        links = finger(arg)
        for link in links:
            try:
                print link['rel']
                print '\t%s' % link['href']
            except KeyError:
                continue

if __name__ == '__main__':
    run()
